In [3]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

print(iris.data)
print(iris.data.shape)
print(iris.target_names)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
print(digits.data)
print(digits.data.shape)
print(digits.target_names)
print(digits.target)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797, 64)
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 ... 8 9 8]


In [27]:
# 手动划分数据集、测试集
n_test = 100
train_X = digits.data[:-n_test,:]
train_y = digits.target[:-n_test]

test_X = digits.data[-n_test:,:]
y_true = digits.target[-n_test:]
# 选择svm模型
from sklearn import  svm
svm_model=svm.SVC(gamma=0.001,C=100.)
# 训练模型
svm_model.fit(train_X,train_y)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
from sklearn.linear_model import  LogisticRegression

lr_model = LogisticRegression()
# 训练模型
lr_model.fit(train_X,train_y)

C:\Users\Administrator\Anaconda3\envs\tensorFlow\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\envs\tensorFlow\lib\site-packages\sklearn\linear_model\logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
y_pred_svm = svm_model.predict(test_X)
y_pred_lr = lr_model.predict(test_X)

In [30]:
from sklearn.metrics import accuracy_score
print("SVM结果：",accuracy_score(y_true,y_pred_svm))
print("LR结果：",accuracy_score(y_true,y_pred_lr))

SVM结果： 0.98
LR结果： 0.94


In [32]:
import pickle

with open('svm_model.pkl','wb') as f:
    pickle.dump(svm_model,f) 

In [39]:
import numpy as np
from sklearn.model_selection import train_test_split
X = np.random.randint(0,100,(10,4))
y = np.random.randint(0,3,10)
y.sort()

print('样本：')
print(X)
print("标签：",y)

样本：
[[49 51 76 15]
 [34 51 27 29]
 [81 87 39 37]
 [96 34 10 55]
 [93 36 79 83]
 [90 64 72 13]
 [68 77 94  8]
 [ 4 64 16  3]
 [85 49 39 61]
 [53 43  5 32]]
标签： [0 0 0 1 1 1 1 2 2 2]


In [54]:
# 分割数据集、测试集
# random_state 确保每次随机分割得到相同的结果
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/3.,random_state=7)

In [55]:
print('训练集：')
print(X_train)
print(y_train)
print("测试集：")
print(X_test)
print(y_test)

训练集：
[[34 51 27 29]
 [53 43  5 32]
 [ 4 64 16  3]
 [96 34 10 55]
 [68 77 94  8]
 [93 36 79 83]]
[0 2 2 1 1 1]
测试集：
[[85 49 39 61]
 [90 64 72 13]
 [49 51 76 15]
 [81 87 39 37]]
[2 1 0 0]
