In [1]:
import numpy as np

In [11]:
matrix = np.array([
                     [5,10,15],
                     [20,25,30],
                     [35,40,45]
                    ])
print(matrix[:,1])#切片
second_column_25 = (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25,:])

[10 25 40]
[False  True False]
[[20 25 30]]


In [3]:
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [16]:
vector  = np.array([5,10,20,15])
equal_to_ten = (vector == 10)&(vector ==4)
# print(vector[equal_to_ten])
print(equal_to_ten)

[False False False False]
