In [1]:
a  = 3
print(type(a))

<class 'int'>


In [2]:
str_a = str(a)
print(type(str_a))

<class 'str'>


In [7]:
months = []
months.append("a")
months.append("b")
months.append("f")
months.append("d")
months.append("h")
months.append("lh")
print(type(months))
print(months)

<class 'list'>
['a', 'b', 'f', 'd', 'h', 'lh']


In [10]:
print(months[2:])# value at 2,3 index but not 4

['f', 'd', 'h', 'lh']


In [15]:
months=[[1,2,3,4,5],['a','b','c','d']] 
for i in months:
     for j in i:
        print(j)

1
2
3
4
5
a
b
c
d


In [16]:
animals = ['cat','dog','rabbit']
if 'cat' in animals:
    print("cat found")

cat found


In [19]:
# 字典
scores = {} #key value
print(type(scores))
scores['jim'] = 80
scores['sue'] = 85
scores['ann'] = 75
print(scores.keys())
print(scores)

<class 'dict'>
dict_keys(['jim', 'sue', 'ann'])
{'jim': 80, 'sue': 85, 'ann': 75}


In [23]:
pantry = ["apple","orange",'grape','apple','orange','apple','tomato','potato','grape']
pantry_counts={}

for item in pantry:
    if item in pantry_counts:
        pantry_counts[item] = pantry_counts[item]+1
    else:
        pantry_counts[item] = 1
print(pantry_counts)

{'apple': 3, 'orange': 2, 'grape': 2, 'tomato': 1, 'potato': 1}


In [26]:
import numpy
# world_alcohol = numpy.gengromtxt("",delimiter = ',',dtype = str)
# print(type(world_alcohol))
# print(world_alcohol)
print(help(numpy.genfromtxt))

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
   

In [29]:
vector = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print (vector)
print (matrix)               

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [31]:
print(vector.shape)#几行几列
print(matrix.shape)

(4,)
(3, 3)


In [34]:
numbers = numpy.array([1,2,3,4.0])
print(numbers)
numbers.dtype

[1. 2. 3. 4.]


dtype('float64')

In [47]:
world_alcohol = numpy.genfromtxt('world_alcohol.txt',delimiter=',',dtype=str,skip_header=1)
print(world_alcohol)

["['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']"
 "['1986' 'Americas' 'Uruguay' 'Other' '0.5']"
 "['1987' 'Africa' 'Malawi' 'Other' '0.75']"
 "['1989' 'Americas' 'Bahamas' 'Wine' '1.5']"
 "['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]"]


In [49]:
print(world_alcohol.shape)
uruguay_other_1986 = world_alcohol[1][4]
third_country = world_alcohol[2][2]
print(uruguay_other_1986)
print(third_country)

(5,)
8
1


In [50]:
vetor = numpy.array([5,10,15,20])
print(vector[0:3])

[ 5 10 15]


In [58]:
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]
                     ])
# print(matrix[:,1]) # 行:列
# print(matrix[:,0:2])#前两列
print(matrix[1:3,0:2])#[[1到3行)：[0到1列)]

[[20 25]
 [35 40]]


In [66]:
vector = numpy.array([5,10,15,20])
vl = vector.min()
print(vl)
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
matrix.sum(axis=1)

5


array([ 30,  75, 120])

In [67]:
matrix.sum(axis=0)

array([60, 75, 90])

In [68]:
import numpy as np
print (np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [70]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [71]:
a.shape

(3, 5)

In [72]:
a.ndim

2

In [73]:
a.dtype.name

'int32'

In [74]:
a.size

15

In [75]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.ones((4,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [83]:
np.random.random((2,3))

array([[0.29865937, 0.14953145, 0.20259609],
       [0.64491324, 0.62129025, 0.24447625]])

In [84]:
from numpy import  pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [88]:
a = np.array([29,30,40,50])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
c = c-1
print(c)
b**2

[29 30 40 50]
[0 1 2 3]
[29 29 38 47]
[28 28 37 46]


array([0, 1, 4, 9], dtype=int32)

In [91]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A)
print('--------')
print(B)
print('--------')
print(A*B)
print('--------')
print(np.dot(A,B))

[[1 1]
 [0 1]]
--------
[[2 0]
 [3 4]]
--------
[[2 0]
 [0 4]]
--------
[[5 4]
 [3 4]]


In [95]:
a = np.array([
              [6,7,2,9],
              [6,0,5,2],
              [9,0,9,6]
             ])
print(a)
print('----------')
a.shape = (6,2)
print(a)
print(a.T)

[[6 7 2 9]
 [6 0 5 2]
 [9 0 9 6]]
----------
[[6 7]
 [2 9]
 [6 0]
 [5 2]
 [9 0]
 [9 6]]
[[6 2 6 5 9 9]
 [7 9 0 2 0 6]]


In [99]:
a = np.floor(10*np.random.random((2,3)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('----')
print(b)
print('----')
print(np.hstack((a,b)))
a = np.floor(10*np.random.random((2,12)))
print(a)
print('-----')
print(np.hsplit(a,3))
print('------')


[[9. 6. 4.]
 [7. 3. 7.]]
----
[[8. 6.]
 [4. 9.]]
----
[[9. 6. 4. 8. 6.]
 [7. 3. 7. 4. 9.]]
[[0. 4. 2. 7. 7. 3. 9. 3. 6. 3. 8. 9.]
 [2. 2. 3. 8. 9. 5. 1. 8. 9. 3. 3. 4.]]
-----
[array([[0., 4., 2., 7.],
       [2., 2., 3., 8.]]), array([[7., 3., 9., 3.],
       [9., 5., 1., 8.]]), array([[6., 3., 8., 9.],
       [9., 3., 3., 4.]])]
------


In [101]:
import numpy as np
data = np.sin(np.arange(20).reshape(5,4))
print(data)
ind = data.argmax(axis=0)
print(ind)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]


In [111]:
a = np.arange(0,40,10)
print(a)
b = np.tile(a,(4,2))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [112]:
a = np.array([[4,3,5],[1,2,1]])
print(a)
print('--------')

[[4 3 5]
 [1 2 1]]
--------


In [114]:
b = np.sort(a,axis=0)
print(b)

[[1 2 1]
 [4 3 5]]
