In [1]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [2]:
from sklearn import datasets
iris =datasets.load_iris()

In [4]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
# 切分数据集
Xtrain,Xtest,Ytrain,Ytest = train_test_split(iris.data
                                             ,iris.target
                                             ,random_state=42)


In [13]:
Xtrain.shape

(112, 4)

In [14]:
# 建模
clf = GaussianNB()
clf = clf.fit(Xtrain,Ytrain)

In [15]:
# 在测试集上执行预测，proba导出的是每个样本属于某类的概率
clf.predict(Xtest)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0,
       2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [16]:
clf.predict_proba(Xtest)#每一类的概率都列出 ，朴素贝叶斯基于概率分类 把概率最大的类作为该类的标签

array([[  5.97926853e-094,   9.95499546e-001,   4.50045384e-003],
       [  1.00000000e+000,   1.52146968e-013,   1.07136902e-020],
       [  1.71330808e-299,   6.04667826e-012,   1.00000000e+000],
       [  2.88508207e-096,   9.76485329e-001,   2.35146713e-002],
       [  1.36797133e-109,   8.51147229e-001,   1.48852771e-001],
       [  1.00000000e+000,   4.74962788e-013,   4.28854236e-021],
       [  3.25153316e-053,   9.99959350e-001,   4.06500520e-005],
       [  1.09216160e-176,   1.05015117e-006,   9.99998950e-001],
       [  3.27169186e-098,   9.93646597e-001,   6.35340277e-003],
       [  1.17401351e-060,   9.99944993e-001,   5.50073382e-005],
       [  1.00765817e-153,   5.02929583e-004,   9.99497070e-001],
       [  1.00000000e+000,   7.95517827e-017,   5.80301835e-025],
       [  1.00000000e+000,   1.83324108e-016,   2.96899989e-024],
       [  1.00000000e+000,   1.81709952e-016,   2.19054140e-024],
       [  1.00000000e+000,   2.58611124e-016,   6.24907433e-024],
       [  

In [17]:
# 测试准确率
accuracy_score(Ytest,clf.predict(Xtest))

1.0

In [18]:
# 手写测试
import numpy as np
import pandas as pd 
import random

In [23]:
dataSet = pd.read_csv('python/iris.data.csv',header=None)
dataSet.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [24]:
dataSet.shape

(150, 5)

In [45]:
# 随机切分训练集喝测试集
def randSplit(dataSet,rate):
    l = list(dataSet.index)#提取出索引
    random.shuffle(l)#随机打乱索引
    dataSet.index = l#将打乱的索引重新复制给原数据集
    n = dataSet.shape[0]#总行数
    m = int(n * rate)#训练集的数量
    train = dataSet.loc[range(m),:]#提取前m个记录作为训练集
    test = dataSet.loc[range(m,n),:]#剩下的作为测试集
    dataSet.index = range(dataSet.shape[0])#更新测试集的索引
    test.index = range(test.shape[0])
    return train,test

In [28]:
l= list(dataSet.index)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]


In [30]:
random.shuffle(l)
dataSet.index = l

In [33]:
n = dataSet.shape[0]#总行数
m = int(n * 0.8)#训练集的数量

In [34]:
train = dataSet.loc[range(m),:]#0到m行，所有列

In [35]:
train

0    1    2    3                4
0    5.1  3.3  1.7  0.5      Iris-setosa
1    5.8  2.7  5.1  1.9   Iris-virginica
2    6.3  2.3  4.4  1.3  Iris-versicolor
3    6.8  2.8  4.8  1.4  Iris-versicolor
4    5.0  3.5  1.3  0.3      Iris-setosa
5    5.6  3.0  4.1  1.3  Iris-versicolor
6    6.1  2.9  4.7  1.4  Iris-versicolor
7    4.9  3.1  1.5  0.1      Iris-setosa
8    5.1  3.4  1.5  0.2      Iris-setosa
9    7.7  3.0  6.1  2.3   Iris-virginica
10   5.9  3.0  5.1  1.8   Iris-virginica
11   6.0  3.0  4.8  1.8   Iris-virginica
12   5.4  3.7  1.5  0.2      Iris-setosa
13   5.9  3.0  4.2  1.5  Iris-versicolor
14   5.0  2.0  3.5  1.0  Iris-versicolor
15   5.3  3.7  1.5  0.2      Iris-setosa
16   5.5  4.2  1.4  0.2      Iris-setosa
17   6.3  2.7  4.9  1.8   Iris-virginica
18   5.8  4.0  1.2  0.2      Iris-setosa
19   7.7  3.8  6.7  2.2   Iris-virginica
20   6.8  3.0  5.5  2.1   Iris-virginica
21   4.9  3.1  1.5  0.1      Iris-setosa
22   4.7  3.2  1.6  0.2      Iris-setosa
23   6.2  2.9  4.3  1.3  Iris-versicolor
24   6.1  3.0  4.9  1.8   Iris-virginica
25   6.0  2.7  5.1  1.6  Iris-versicolor
26   5.0  3.0  1.6  0.2      Iris-setosa
27   7.6  3.0  6.6  2.1   Iris-virginica
28   5.4  3.9  1.7  0.4      Iris-setosa
29   5.0  3.5  1.6  0.6      Iris-setosa
..   ...  ...  ...  ...              ...
90   6.4  3.2  4.5  1.5  Iris-versicolor
91   4.9  2.5  4.5  1.7   Iris-virginica
92   7.2  3.6  6.1  2.5   Iris-virginica
93   6.7  3.1  4.7  1.5  Iris-versicolor
94   7.2  3.0  5.8  1.6   Iris-virginica
95   5.9  3.2  4.8  1.8  Iris-versicolor
96   6.7  3.3  5.7  2.5   Iris-virginica
97   7.2  3.2  6.0  1.8   Iris-virginica
98   6.1  2.6  5.6  1.4   Iris-virginica
99   5.7  2.9  4.2  1.3  Iris-versicolor
100  5.2  3.4  1.4  0.2      Iris-setosa
101  5.8  2.7  5.1  1.9   Iris-virginica
102  5.6  2.9  3.6  1.3  Iris-versicolor
103  5.8  2.7  4.1  1.0  Iris-versicolor
104  6.0  2.2  4.0  1.0  Iris-versicolor
105  6.4  2.8  5.6  2.2   Iris-virginica
106  6.3  3.3  4.7  1.6  Iris-versicolor
107  5.8  2.6  4.0  1.2  Iris-versicolor
108  6.7  3.0  5.0  1.7  Iris-versicolor
109  5.4  3.0  4.5  1.5  Iris-versicolor
110  5.7  4.4  1.5  0.4      Iris-setosa
111  6.4  2.7  5.3  1.9   Iris-virginica
112  7.3  2.9  6.3  1.8   Iris-virginica
113  4.4  2.9  1.4  0.2      Iris-setosa
114  6.6  2.9  4.6  1.3  Iris-versicolor
115  6.1  2.8  4.0  1.3  Iris-versicolor
116  7.7  2.6  6.9  2.3   Iris-virginica
117  4.6  3.4  1.4  0.3      Iris-setosa
118  4.8  3.4  1.6  0.2      Iris-setosa
119  5.1  3.8  1.5  0.3      Iris-setosa

[120 rows x 5 columns]

In [40]:
test = dataSet.loc[range(m,n),:]#剩下的作为测试集
test.index = range(test.shape[0])

In [41]:
test

0    1    2    3               4
0   6.9  3.2  5.7  2.3  Iris-virginica
1   5.6  2.8  4.9  2.0  Iris-virginica
2   7.7  2.8  6.7  2.0  Iris-virginica
3   6.3  2.7  4.9  1.8  Iris-virginica
4   6.7  3.3  5.7  2.1  Iris-virginica
5   7.2  3.2  6.0  1.8  Iris-virginica
6   6.2  2.8  4.8  1.8  Iris-virginica
7   6.1  3.0  4.9  1.8  Iris-virginica
8   6.4  2.8  5.6  2.1  Iris-virginica
9   7.2  3.0  5.8  1.6  Iris-virginica
10  7.4  2.8  6.1  1.9  Iris-virginica
11  7.9  3.8  6.4  2.0  Iris-virginica
12  6.4  2.8  5.6  2.2  Iris-virginica
13  6.3  2.8  5.1  1.5  Iris-virginica
14  6.1  2.6  5.6  1.4  Iris-virginica
15  7.7  3.0  6.1  2.3  Iris-virginica
16  6.3  3.4  5.6  2.4  Iris-virginica
17  6.4  3.1  5.5  1.8  Iris-virginica
18  6.0  3.0  4.8  1.8  Iris-virginica
19  6.9  3.1  5.4  2.1  Iris-virginica
20  6.7  3.1  5.6  2.4  Iris-virginica
21  6.9  3.1  5.1  2.3  Iris-virginica
22  5.8  2.7  5.1  1.9  Iris-virginica
23  6.8  3.2  5.9  2.3  Iris-virginica
24  6.7  3.3  5.7  2.5  Iris-virginica
25  6.7  3.0  5.2  2.3  Iris-virginica
26  6.3  2.5  5.0  1.9  Iris-virginica
27  6.5  3.0  5.2  2.0  Iris-virginica
28  6.2  3.4  5.4  2.3  Iris-virginica
29  5.9  3.0  5.1  1.8  Iris-virginica

In [46]:
train,test = randSplit(dataSet,0.8)

In [47]:
train

0    1    2    3                4
0    6.4  2.9  4.3  1.3  Iris-versicolor
1    5.6  2.7  4.2  1.3  Iris-versicolor
2    6.2  3.4  5.4  2.3   Iris-virginica
3    5.5  4.2  1.4  0.2      Iris-setosa
4    6.3  2.5  4.9  1.5  Iris-versicolor
5    5.8  2.7  5.1  1.9   Iris-virginica
6    6.1  2.9  4.7  1.4  Iris-versicolor
7    5.7  4.4  1.5  0.4      Iris-setosa
8    4.8  3.0  1.4  0.3      Iris-setosa
9    5.0  3.0  1.6  0.2      Iris-setosa
10   6.7  3.0  5.0  1.7  Iris-versicolor
11   6.1  2.8  4.7  1.2  Iris-versicolor
12   6.4  2.8  5.6  2.1   Iris-virginica
13   6.1  3.0  4.9  1.8   Iris-virginica
14   4.9  3.1  1.5  0.1      Iris-setosa
15   5.4  3.9  1.3  0.4      Iris-setosa
16   6.3  2.9  5.6  1.8   Iris-virginica
17   4.6  3.2  1.4  0.2      Iris-setosa
18   5.3  3.7  1.5  0.2      Iris-setosa
19   5.5  3.5  1.3  0.2      Iris-setosa
20   6.3  3.3  4.7  1.6  Iris-versicolor
21   6.4  2.7  5.3  1.9   Iris-virginica
22   6.9  3.2  5.7  2.3   Iris-virginica
23   6.8  2.8  4.8  1.4  Iris-versicolor
24   5.1  3.4  1.5  0.2      Iris-setosa
25   6.7  2.5  5.8  1.8   Iris-virginica
26   6.5  2.8  4.6  1.5  Iris-versicolor
27   6.0  2.7  5.1  1.6  Iris-versicolor
28   5.0  2.3  3.3  1.0  Iris-versicolor
29   5.8  2.6  4.0  1.2  Iris-versicolor
..   ...  ...  ...  ...              ...
90   5.1  3.5  1.4  0.3      Iris-setosa
91   6.4  3.2  5.3  2.3   Iris-virginica
92   6.6  3.0  4.4  1.4  Iris-versicolor
93   5.1  3.7  1.5  0.4      Iris-setosa
94   5.9  3.0  4.2  1.5  Iris-versicolor
95   6.3  2.5  5.0  1.9   Iris-virginica
96   5.7  2.5  5.0  2.0   Iris-virginica
97   6.1  3.0  4.6  1.4  Iris-versicolor
98   6.9  3.1  4.9  1.5  Iris-versicolor
99   5.2  3.4  1.4  0.2      Iris-setosa
100  6.0  2.2  5.0  1.5   Iris-virginica
101  5.0  2.0  3.5  1.0  Iris-versicolor
102  4.8  3.1  1.6  0.2      Iris-setosa
103  4.9  2.5  4.5  1.7   Iris-virginica
104  5.0  3.6  1.4  0.2      Iris-setosa
105  5.8  2.7  3.9  1.2  Iris-versicolor
106  5.5  2.4  3.8  1.1  Iris-versicolor
107  5.4  3.9  1.7  0.4      Iris-setosa
108  7.2  3.0  5.8  1.6   Iris-virginica
109  5.9  3.2  4.8  1.8  Iris-versicolor
110  4.9  3.1  1.5  0.1      Iris-setosa
111  5.7  3.8  1.7  0.3      Iris-setosa
112  5.7  2.9  4.2  1.3  Iris-versicolor
113  6.7  3.3  5.7  2.5   Iris-virginica
114  6.3  2.8  5.1  1.5   Iris-virginica
115  4.4  2.9  1.4  0.2      Iris-setosa
116  6.7  3.3  5.7  2.1   Iris-virginica
117  6.5  3.2  5.1  2.0   Iris-virginica
118  6.7  3.1  4.7  1.5  Iris-versicolor
119  5.0  3.4  1.5  0.2      Iris-setosa

[120 rows x 5 columns]

In [48]:
test

0    1    2    3                4
0   5.9  3.0  5.1  1.8   Iris-virginica
1   5.1  3.8  1.5  0.3      Iris-setosa
2   6.1  2.6  5.6  1.4   Iris-virginica
3   7.0  3.2  4.7  1.4  Iris-versicolor
4   6.3  2.3  4.4  1.3  Iris-versicolor
5   6.0  2.2  4.0  1.0  Iris-versicolor
6   5.0  3.3  1.4  0.2      Iris-setosa
7   4.9  3.0  1.4  0.2      Iris-setosa
8   5.6  2.9  3.6  1.3  Iris-versicolor
9   7.7  3.8  6.7  2.2   Iris-virginica
10  5.1  3.3  1.7  0.5      Iris-setosa
11  7.1  3.0  5.9  2.1   Iris-virginica
12  6.2  2.8  4.8  1.8   Iris-virginica
13  5.6  2.8  4.9  2.0   Iris-virginica
14  7.3  2.9  6.3  1.8   Iris-virginica
15  6.8  3.2  5.9  2.3   Iris-virginica
16  4.6  3.6  1.0  0.2      Iris-setosa
17  4.3  3.0  1.1  0.1      Iris-setosa
18  6.0  2.9  4.5  1.5  Iris-versicolor
19  5.2  3.5  1.5  0.2      Iris-setosa
20  5.4  3.7  1.5  0.2      Iris-setosa
21  5.8  2.7  5.1  1.9   Iris-virginica
22  5.8  4.0  1.2  0.2      Iris-setosa
23  4.7  3.2  1.6  0.2      Iris-setosa
24  6.0  3.0  4.8  1.8   Iris-virginica
25  5.7  2.6  3.5  1.0  Iris-versicolor
26  4.4  3.0  1.3  0.2      Iris-setosa
27  6.5  3.0  5.2  2.0   Iris-virginica
28  5.0  3.5  1.3  0.3      Iris-setosa
29  5.5  2.4  3.7  1.0  Iris-versicolor

In [49]:
# 朴素贝叶斯分类器
def gnb_classify(train,test):#X[:,  m:n]，即取所有数据的第m到n-1列数据，含左不含右
    labels  = train.iloc[:,-1].value_counts().index#提取训练集的标签种类
    mean = [] #存放每个类别的均值
    std  = [] #存放每个类别的方差
    result = []#存放测试集的预测结果
    for i in labels:
        item = train.loc[train.iloc[:,-1] == i,:]#分别提取出每一种类别
        m = item.iloc[:,:-1].mean()#当前类别的平均值
        s = np.sum((item.iloc[:,:-1]))
        

In [82]:
def loadDataSet():
    postingList=[['my','dog','has','flea','problem','help','please'],
                 ['maybe','not','take','him','to','dog','park','stupid'],
                 ['my','dalmation','is','so','cute','I','love','him'],
                 ['stop','posting','ate','my','steak','how','to','stop','him'],
                 ['mr','licks','ate','my','steak','how','to','stop','him'],
                 ['quit','buying','worthless','dog','food','stupid','garbage']]
    classVec=[0,1,0,1,0,1]
    return postingList,classVec

In [83]:
dataSet,classVec = loadDataSet()

In [84]:
dataSet

[['my', 'dog', 'has', 'flea', 'problem', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid', 'garbage']]

In [85]:
classVec

[0, 1, 0, 1, 0, 1]

In [86]:
def createVocabList(dataSet):
    vocabSet = set()#创建一个空的集合
    for doc in dataSet:#遍历dataSet中的每一条言论
        vocabSet = vocabSet| set(doc)#取并集
        vocabList = list(vocabSet)
    return vocabList

In [87]:
vocabList = createVocabList(dataSet)
print(vocabList)

['has', 'please', 'buying', 'food', 'mr', 'cute', 'him', 'park', 'I', 'how', 'licks', 'take', 'help', 'to', 'love', 'steak', 'worthless', 'stop', 'is', 'my', 'dog', 'stupid', 'flea', 'not', 'posting', 'quit', 'maybe', 'so', 'problem', 'ate', 'dalmation', 'garbage']


In [88]:
# 生成词向量
def setOfWorlds2Vec(vocabList,inputSet):
    returnVec =[0]*len(vocabList)#创建一个其中所含元素都为0的向量
    for word in inputSet:#遍历每个词条
        if word in vocabList:#如果词条存在于词汇表中，则变为1
            returnVec[vocabList.index(word)]=1
        else:
            print(f"{word}is not in my Vocabulary!")
    return returnVec#返回文档向量

In [89]:
def get_trainMat(dataSet):
    trainMat = []#初始化向量列表
    vocabList = createVocabList(dataSet)#生成词汇表
    for inputSet in dataSet:#遍历样本词条中的每一条样本
        returnVec = setOfWorlds2Vec(vocabList,inputSet)#将当前词条向量化
        trainMat.append(returnVec)#追加到向量列表中
    return trainMat

In [90]:
trainMat = get_trainMat(dataSet)

In [91]:
print(trainMat)

[[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]]


In [92]:
def trainNB(trainMat,classVec):
    n = len(trainMat)#计算训练的文档数目
    m = len(trainMat[0])#计算每篇文档的词条数
    pAb = sum(classVec)/n#文档属于侮辱类的概率
    p0Num = np.zeros(m)#词条出现数初始化为0
    p1Num = np.zeros(m)#词条出现数初始化为0
    p0Denom = 0#分母初始化为0
    p1Denom = 0#分母初始化为0
    for i in range(n):#遍历每一个文档
        if classVec[i] == 1:#统计属于侮辱类的条件概率所需的数据
            p1Num +=trainMat[i]
            p1Denom += sum(trainMat[i])
        else:
            p0Num += trainMat[i]
            p0Denom +=sum(trainMat[i])
    p1V = p1Num/p1Denom
    p0V = p0Num/p0Denom
    return p0V,p1V,pAb#返回属于非侮辱类，侮辱类和文档属于侮辱类的概率

In [93]:
p0V,p1V,pAb = trainNB(trainMat,classVec)

In [94]:
p0V

array([ 0.04166667,  0.04166667,  0.        ,  0.        ,  0.04166667,
        0.04166667,  0.08333333,  0.        ,  0.04166667,  0.04166667,
        0.04166667,  0.        ,  0.04166667,  0.04166667,  0.04166667,
        0.04166667,  0.        ,  0.04166667,  0.04166667,  0.125     ,
        0.04166667,  0.        ,  0.04166667,  0.        ,  0.        ,
        0.        ,  0.        ,  0.04166667,  0.04166667,  0.04166667,
        0.04166667,  0.        ])

In [95]:
p1V

array([ 0.        ,  0.        ,  0.04347826,  0.04347826,  0.        ,
        0.        ,  0.08695652,  0.04347826,  0.        ,  0.04347826,
        0.        ,  0.04347826,  0.        ,  0.08695652,  0.        ,
        0.04347826,  0.04347826,  0.04347826,  0.        ,  0.04347826,
        0.08695652,  0.08695652,  0.        ,  0.04347826,  0.04347826,
        0.04347826,  0.04347826,  0.        ,  0.        ,  0.04347826,
        0.        ,  0.04347826])

In [96]:
pAb

0.5

In [97]:
from functools import reduce

In [98]:
def classifyNB(vec2Classify,p0V,p1V,pAb):
    p1 = reduce(lambda x,y:x*y,vec2Classify*p1V)*pAb #对应元素相乘
    p0 = reduce(lambda x,y:x*y,vec2Classify*p0V)*(1-pAb)
    print('p0:',p0)
    print('p1:',p1)
    if(p1>p0):
        return 1
    else :
        return 0

In [99]:
def testingNB(testVec):
    dataSet,classVec = loadDataSet()#创建实验样本
    vocabList = createVocabList(dataSet)#创建词汇表
    trainMat = get_trainMat(dataSet)#将实验样本向量化
    p0V,p1V,pAb = trainNB(trainMat,classVec)#测试样本向量化
    thisone = setOfWorlds2Vec(vocabList,testVec)#测试样本向量化
    if classifyNB(thisone,p0V,p1V,pAb):
        print(testVec,'属于侮辱类')
    else:
        print(testVec,'属于非侮辱类')

In [100]:
#测试样本1
testVec1 =['love','my','dalmation']
testingNB(testVec1)

p0: 0.0
p1: 0.0
['love', 'my', 'dalmation'] 属于非侮辱类


In [101]:
#测试样本2
testVec1 =['stupid','garbage']
testingNB(testVec1)

p0: 0.0
p1: 0.0
['stupid', 'garbage'] 属于非侮辱类


In [102]:
def trainNB(trainMat,classVec):
    n = len(trainMat)#计算训练的文档数目
    m = len(trainMat[0])#计算每篇文档的词条数
    pAb = sum(classVec)/n#文档属于侮辱类的概率
    p0Num = np.ones(m)#词条出现数初始化为0
    p1Num = np.ones(m)#词条出现数初始化为0
    p0Denom = 2#分母初始化为2
    p1Denom = 2#分母初始化为2
    for i in range(n):#遍历每一个文档
        if classVec[i] == 1:#统计属于侮辱类的条件概率所需的数据
            p1Num +=trainMat[i]
            p1Denom += sum(trainMat[i])
        else:
            p0Num += trainMat[i]
            p0Denom +=sum(trainMat[i])
    p1V =np.log(p1Num/p1Denom)
    p0V =np.log(p0Num/p0Denom)
    return p0V,p1V,pAb#返回属于非侮辱类，侮辱类和文档属于侮辱类的概率

In [103]:
p0V,p1V,pAb = trainNB(trainMat,classVec)

In [104]:
p0V

array([-2.56494936, -2.56494936, -3.25809654, -3.25809654, -2.56494936,
       -2.56494936, -2.15948425, -3.25809654, -2.56494936, -2.56494936,
       -2.56494936, -3.25809654, -2.56494936, -2.56494936, -2.56494936,
       -2.56494936, -3.25809654, -2.56494936, -2.56494936, -1.87180218,
       -2.56494936, -3.25809654, -2.56494936, -3.25809654, -3.25809654,
       -3.25809654, -3.25809654, -2.56494936, -2.56494936, -2.56494936,
       -2.56494936, -3.25809654])

In [105]:
def classifyNB(vec2Classify,p0V,p1V,pAb):
    p1 = sum(vec2Classify*p1V)+np.log(pAb) #对应元素相乘
    p0 = sum(vec2Classify*p1V)+np.log(1-pAb)
    if(p1>p0):
        return 1
    else :
        return 0

In [106]:
#测试样本1
testVec1 =['love','my','dalmation']
testingNB(testVec1)

['love', 'my', 'dalmation'] 属于非侮辱类


In [107]:
#测试样本2
testVec1 =['stupid','garbage']
testingNB(testVec1)

['stupid', 'garbage'] 属于非侮辱类


In [108]:
def testingNB(testVec):
    dataSet,classVec = loadDataSet()#创建实验样本
    vocabList = createVocabList(dataSet)#创建词汇表
    trainMat = get_trainMat(dataSet)#将实验样本向量化
    p0V,p1V,pAb = trainNB(trainMat,classVec)#测试样本向量化
    thisone = setOfWorlds2Vec(vocabList,testVec)#测试样本向量化
    if classifyNB(thisone,p0V,p1V,pAb):
        print(testVec,'属于侮辱类')
    else:
        print(testVec,'属于非侮辱类')

In [109]:
#测试样本1
testVec1 =['love','my','dalmation']
testingNB(testVec1)

['love', 'my', 'dalmation'] 属于非侮辱类


In [110]:
#测试样本1
testVec1 =['stupid','garbage']
testingNB(testVec1)

['stupid', 'garbage'] 属于非侮辱类
