In [42]:
import numpy as np

In [43]:
X = np.array([i for i in range(15)])

In [44]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
np.random.shuffle(X)

In [46]:
X

array([ 3,  1, 12,  8,  6, 10,  4,  0, 11, 14, 13,  5,  2,  9,  7])

In [47]:
np.argmax(X)

9

In [48]:
np.argmin(X)

7

In [49]:
np.var(X)

18.666666666666668

In [50]:
np.std(X)

4.320493798938574

In [51]:
np.mean(X)

7.0

In [52]:
np.sum(X)

105

In [53]:
np.sort(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
X

array([ 3,  1, 12,  8,  6, 10,  4,  0, 11, 14, 13,  5,  2,  9,  7])

In [55]:
X = np.sort(X)

In [56]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.random.shuffle(X)

In [58]:
X

array([11,  6, 13,  4,  5, 14,  0,  3,  2,  7,  1,  8,  9, 12, 10])

In [59]:
np.argsort(X)

array([ 6, 10,  8,  7,  3,  4,  1,  9, 11, 12, 14,  0, 13,  2,  5],
      dtype=int64)

In [60]:
np.partition(X,5)

array([ 0,  1,  2,  4,  3,  5,  8,  6,  9,  7, 10, 14, 13, 12, 11])

In [61]:
  import numpy as np

In [62]:
x = np.arange(16)

In [63]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
x[3]

3

In [65]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [67]:
x[3:5:7]

array([3])

In [69]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [70]:
ind = [3,5,8]

In [71]:
ind

[3, 5, 8]

In [72]:
type(ind)

list

In [73]:
ind = np.array([[0,2],
                [1,3]])

In [74]:
x[ind]

array([[0, 2],
       [1, 3]])

In [83]:
X = np.arange(16)

In [84]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
X = X.reshape(4,-1)

In [86]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [88]:
col = [True,False,True,True]

In [89]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

#### numpy.array 比较

In [90]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
X.reshape((1,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [93]:
X < 3

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [94]:
X > 3

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])